name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.operating-system }}

    environment: 
      name: production
      url: https://sigui.ci

    permissions:
      id-token: write
      contents: read
    
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        bun-version: [1.0.3]
    
    name: ğŸš€ Deploy sigui.ci to ${{ matrix.operating-system }} on ${{ matrix.bun-version }}
    
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Node.JS
        uses: oven-sh/setup-bun@v1
        with:
          version: ${{ matrix.bun-version }}

      - name: âš¡ï¸ Install dependencies
        run: bun install

      - name: âœ… Check files
        run: bun run check

      - name: ğŸ± Build assets
        run: bun run build

      - name: ğŸ“‚ Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: sigui
          entrypoint: server/entry.mjs
          root: dist
