name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.operating-system }}

    environment: 
      name: production
      url: https://sigui.ci

    permissions:
      id-token: write
      contents: read
    
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [18.18.0]
    
    name: ğŸš€ Deploy sigui.ci to ${{ matrix.operating-system }} on ${{ matrix.node-version }}
    
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: âš¡ï¸ Install dependencies
        run: |
          corepack  enable
          pnpm install

      - name: âœ… Check files
        run: pnpm check

      - name: ğŸ± Build assets
        run: pnpm build

      - name: ğŸ“‚ Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: sigui
          entrypoint: server/entry.mjs
          root: dist
