on: push

name: Deploy

jobs:
  deploy:
    runs-on: ${{ matrix.operating-system }}
    
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [16.20.0]
    
    name: ğŸš€ Deploy sigui.ci to ${{ matrix.operating-system }} on ${{ matrix.node-version }}
    
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: âš¡ï¸ Install dependencies
        run: |
          npm i -g pnpm
          pnpm install

      - name: âœ… Check files
        run: pnpm check

      - name: ğŸ± Compile assets
        run: pnpm build

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.sikessem.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          timeout: 90000
